config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  resources :vehicules do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, except: [:new, :create]

  scope :dashboard do
    resources :bookings, only: [:index], as: 'dashboard'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord

  #MODEL VALIDATIONS
  validates :start_date, presence: true
  validates :end_time, presence: true

  # DB RELATIONSHIPS
  belongs_to :user
  belongs_to :vehicule

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # MODEL VALIDATIONS
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, uniqueness: true
  # DB REALTIONSHIPS
  has_many :vehicules, dependent: :destroy
  has_many :bookings
  # AVATAR
  has_one_attached :photo
end

app/models/vehicule.rb
class Vehicule < ApplicationRecord

  # MODEL VALIDATIONS
  validates :brand, presence: true
  validates :capacity, presence: true
  validates :features, presence: true
  validates :location, presence: true
  validates :price, presence: true

  # DB RELATIONSHIPS
  belongs_to :user
  has_many :bookings

  # CLOUDINARY PHOTOS OF THE VEHICULE
  has_many_attached :photos

  # GEOCODING
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  # SEARCHING PG_SEARCH
  include PgSearch::Model
  pg_search_scope :search_by_brand_and_location,
    against: [ :brand, :location ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

end

app/controllers/bookings_controller.rb
require 'date'
class BookingsController < ApplicationController

  def new
    @vehicule = Vehicule.find(params[:vehicule_id])
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = Booking.new(strong_params)
    @vehicule = Vehicule.find(params[:vehicule_id])
    @booking.user_id = current_user.id
    @booking.vehicule_id = @vehicule.id
    authorize @booking

   #CAN NOT ALLOW THE USER TO BOOK A CAR IF THE ENDING DATE IS BEFORE THE STARTING DATE

    if @booking.end_time < @booking.start_date
      redirect_to vehicule_path(@vehicule)
      flash.now[:notice] = 'Sorry, starting date needs to be before the ending date'

    else

      if @booking.save
        redirect_to dashboard_index_path
        flash.now[:notice] = "#{current_user.first_name}, you have successfully booked #{@vehicule.brand}!"
      else
        flash[:alert] = @booking.errors.full_messages.first
        redirect_to vehicule_path(@vehicule)
      end

    end
  end

  def show
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def index
    @bookings = policy_scope(Booking).order(created_at: :desc)
    @current_user_vehicules = current_user.vehicules
    @received_bookings = []
    @current_user_vehicules.each do |vehicule|
      @received_bookings.push(vehicule.bookings)
    end
  end

  private

  def strong_params
    params.require(:booking).permit(:start_date, :end_time)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @latest_vehicules = Vehicule.order(created_at: :desc).limit(3)
    if current_user
      redirect_to vehicules_path
    end
  end

end

app/controllers/vehicules_controller.rb
class VehiculesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index

    #Basic search
    if params[:query].present?
      @vehicules = policy_scope(Vehicule).search_by_brand_and_location(params[:query])
    else
      @vehicules = policy_scope(Vehicule).all
    end

    # MAPBOX-GEOCODING
    @markers = @vehicules.geocoded.map do |vehicule|
      {
        lat: vehicule.latitude,
        lng: vehicule.longitude
      }
    end
  end

  def show
    @vehicule = Vehicule.find(params[:id])
    @features = @vehicule.features
    @display_features = @features.split(", ")
    authorize @vehicule

  end

  def new
    @vehicule = Vehicule.new
    authorize @vehicule
  end

  def create
    @vehicule = Vehicule.new(vehicule_params)
    authorize @vehicule
    @vehicule.user_id = current_user.id
    if @vehicule.save!
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def vehicule_params
    params.require(:vehicule).permit(:brand, :location, :features, :photo, :capacity, :price, :vehicule_category)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/vehicules_helper.rb
module VehiculesHelper
end

app/views/bookings/index.html.erb
<h1><%= current_user.first_name %>DASHBOARD</h1>
<h4>BOOKINGS AS A GUEST (user_id: <%= current_user.id %>)</h4>
<% if current_user.bookings.any? %>
  <ul>
    <% count = 1 %>
    <% @bookings.each do |booking| %>
      <strong>Booking nº: <%= count %></strong>
      <li>
        Starting date: <%= booking.start_date %>
      </li>
      <li>
        Ending date: <%= booking.end_time %>
      </li>
      <li>
        Vehicule: <%= booking.vehicule.brand %>
      </li>
      <li>
        Status: <%= booking.status %>
      </li>
      <% count += 1 %>
    <% end %>
  </ul>
<% else %>
  <p>No bookings yet.</p>
<% end %>

<h4>BOOKINGS AS A HOST</h4>
  <ul>
    <% count_2 = 1 %>
    <% @received_bookings.each do |booking_inst| %>
        <% booking_inst.each do |booking| %>
        <% if booking.present? %>
          <strong>Booking nº: <%= count_2 %></strong>
          <li>Starting date: <%= booking.start_date %></li>
          <li>Ending date: <%= booking.end_time %></li>
          <li>Vehicule: <%= booking.vehicule.brand %></li>
          <li>Status: <%= booking.status %></li>
          <li>Guest: <%= booking.user.first_name %> <%= booking.user.last_name %></li>
          <% count_2 +=1  %>
        <% else %>
          <% next %>
        <% end %>
      <% end %>
    <% end %>
  </ul>

app/views/bookings/new.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<h1>NEW BOOKING!</h1>

<%= simple_form_for [@vehicule, @booking] do |form|%>
 <%= form.input :start_date, as: :date, label: 'Select starting date' %>
 <%= form.input :end_time, as: :date, label: 'Select ending date' %>
 <%= form.button :submit %>
<% end %>

app/views/bookings/show.html.erb
<BR></BR>
<BR></BR>
<BR></BR>
<BR></BR>
<BR></BR>
<BR></BR>
<BR></BR>
<h1>BOOKING SHOW PAGE!</h1>

app/views/landing_page/sections/_banner.html.erb
<section class="banner">
  <div class="banner-text">
    <p class="punchline">
        Enjoy the ride.
    </p>
    <p class="secondary-punchline">
      Rent from locals and go for the adventure.
    </p>
  </div>
</section>

app/views/landing_page/sections/_landing-header.html.erb
  <section class="landing-header">
    <hr class="left-line"></hr>
    <p class="logo" id="logo">drivss</p>
    <hr class="right-line"></hr>
  </section>
<script>
  const landingHeaderAnimation2 = () => {
  const logoHeader = document.querySelector(".landing-header");
  const logo = document.querySelector('.logo');
  const hrLeft = document.querySelector('.left-line');
  const hrRight = document.querySelector('.right-line');
    window.addEventListener("scroll",(e)=> {
      if (window.pageYOffset >= 25) {
        logoHeader.style.backgroundColor = "white";
        logo.style.color = "#6D326D";
        logoHeader.style.boxShadow = "0 0 15px rgba(0,0,0,0.2)";
        hrLeft.style.backgroundColor ="#6D326D";
        hrRight.style.backgroundColor ="#6D326D";
      } else if (window.pageYOffset < 25) {
        logoHeader.style.backgroundColor = "transparent";
        logo.style.color="white";
        logoHeader.style.boxShadow = "0 0 0 rgba(0,0,0,0)";
        hrLeft.style.backgroundColor ="white";
        hrRight.style.backgroundColor ="white";
      }
    });
};
landingHeaderAnimation2();
</script>

app/views/landing_page/sections/_sec-one.html.erb
<section class="sec-one">
  <p class="sec-one-text">
    Your new way to rent.
  </p>
  <div class="three-div-wrapper">
    <div class="square">
      <p three-divs-titles>Powered by locals</p>
      <lottie-player src="https://assets7.lottiefiles.com/packages/lf20_K474ba.json" background="transparent"  speed="1"  style="width: 300px; height: 300px;" loop autoplay></lottie-player>
    </div>
    <div class="square">
      <p three-divs-titles>No paperwork</p>
      <lottie-player src="https://assets1.lottiefiles.com/packages/lf20_FizrwJ.json" background="transparent"  speed="1"  style="width: 300px; height: 300px;" loop autoplay></lottie-player>
    </div>
    <div class="square">
      <p three-divs-titles>Whatever you need</p>
      <lottie-player src="https://assets8.lottiefiles.com/packages/lf20_QPewua.json" background="transparent"  speed="1"  style="width: 300px; height: 300px;" loop autoplay></lottie-player>
    </div>
  </div>
</section>

app/views/landing_page/sections/_sec-three.html.erb
<section class="sec-three">
  <div class="sec-three-text">
    <h1 class="sec-three-title">Own a car? Put it to work for you!</h1>
    <p class="sec-three-description">
      It’s a fact: The typical car is parked 95 percent of the time.<br>
      <span>Earn up to €800 per month by sharing your car with Drivss.</span>
    </p>
    <div class="list-car-btn btn-second">
      <%= link_to "List your car", new_vehicule_path %>
    </div>
  </div>
  <div class="sec-three-animation-wrapper">
    <lottie-player src="https://assets5.lottiefiles.com/packages/lf20_CbDIkR.json" background="transparent"  speed="1"  style="width: 300px; height: 300px;" loop autoplay></lottie-player>
  </div>
</section>
<section class="landing-page-footer">
  <p class="footer-text">Made with ❤️ by DavidHAzagury</p>
</section>

app/views/landing_page/sections/_sec-two.html.erb
<section class="sec-two">
  <h1 sec-two-title>Driveerss latest posts:</h1>
  <div class="landing-cards-wrapper">
    <% @latest_vehicules.each do |vehicule| %>
      <%= link_to vehicule_path(vehicule.id) do  %>
        <div class="landing-card" style="background-image:linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)),url(<%= cl_image_path vehicule.photos.first.key %>)">
          <div class="landind-card-vehicule-details">
            <p class="landing-card-text"><%= vehicule.brand %></p>
            <p class="landing-card-text"><%= vehicule.price %> $/day</p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Drivs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--Bootstrap responsiveness-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <!-- MAPBOX CSS-->
    <link href='https://api.mapbox.com/mapbox-gl-js/v1.12.0/mapbox-gl.css' rel='stylesheet' />
    <!-- GOOGLE FONTS -->
    <link href="https://fonts.googleapis.com/css2?family=Sacramento&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,400;0,500;0,700;0,900;1,400;1,700&display=swap" rel="stylesheet">
    <!-- Lotties animations-->
    <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
  </head>

  <body>
    <%#= render 'shared/navbar' %>
    <%= yield %>
    <% if user_signed_in? %>
      <%= "USER IS SIGN IN" %>
      <%= link_to "LOG OUT", destroy_user_session_path, method: :delete  %>
    <% end %>
    <script src='https://api.mapbox.com/mapbox-gl-js/v1.8.0/mapbox-gl.js'></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/home.html.erb
<div class="img-container">
  <%= render 'landing_page/sections/landing-header' %>
  <%= render 'landing_page/sections/banner' %>
  <div class="btns-container">
    <div class="log-in-btn btn-prim">
      <%= link_to "Log in", new_user_session_path %>
    </div>
    <div class="sign-up-btn btn-second">
      <%= link_to "Sign up", new_user_registration_path %>
    </div>
  </div>
</div>
<%= render 'landing_page/sections/sec-one' %>
<%= render 'landing_page/sections/sec-two' %>
<%= render 'landing_page/sections/sec-three' %>

app/views/shared/_card.html.erb
<div class="cards">
  <div class="card-images">
    <% vehicule.photos.each do |photo| %>
      <%= cl_image_tag photo.key, height:200, width: 300 %>
    <% end %>
  </div>
  <div class="card-description">
    <%= vehicule.brand %>
    <%= vehicule.price %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light fixed-top">
  <%= link_to "drivss", root_path, class: "navbar-brand", id:"logo"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active btn-second">
        <%= link_to "Log in", new_user_session_path, class: "nav-link"  %>
      </li>
      <li class="nav-item active btn-second">
        <%= link_to "Sign Up", new_user_registration_path, class: "nav-link"  %>
      </li>
      <li class="nav-item active btn-prim">
        <%= link_to "List your vehicule", new_vehicule_path, class: "nav-link"  %>
      </li>
    </ul>
  </div>
</nav>

app/views/vehicules/index.html.erb
<div class="page-container">
  <section class="filtering-options">
    <%= form_tag vehicules_path, method: :get do %>
      <%= text_field_tag :query,
      params[:query],
      placeholder: "Find a vehicule"
      %>
      <%= submit_tag "Search", class: "btn btn-primary" %>
    <% end %>
  </section>
  <section class="cards-map-container">
    <div class="cards-container">
      <% @vehicules.each do |vehicule| %>
        <%= link_to vehicule_path(vehicule.id) do  %>
           <%= render 'shared/card', vehicule:vehicule %>
        <% end %>
      <% end %>
    </div>
    <div class="map-container">
      <div id="map"
       style="width: 100%; height: 100%;"
       data-markers="<%= @markers.to_json %>"
       data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </section>
</div>

app/views/vehicules/new.html.erb
<h1> CREATE NEW VEHICULE </h1>
<%= simple_form_for @vehicule do |f| %>
  <%= f.input :brand, label: 'Add the brand of your vehicule', required: "true", error: 'Please specify one' %>
  <%= f.input :features, label: 'Add your vehicule features (separated by ",")',required: "true", error: 'Please specify one' %>
  <%= f.input :location, label:'Add the location of your vehicule', required: "true", error: 'Please specify one' %>
  <%= f.input :capacity, label:'Add the capacity of your vehicule', required: "true", error: 'Please specify one'%>
  <%= f.input :vehicule_category ,label:'Select your vehicule\'s category',  required: "true", :collection => %w[Car SUV Convertible 4X4 Motorbike Truck Van PickUp RV] %>
  <%= f.input :price, label: 'Add the price of your vehicule', required: "true", error: 'Please specify one' %>
 <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= f.button :submit, "List your vehicule" %>
<% end %>

app/views/vehicules/show.html.erb
<h1>SHOW PAGE OF THE VEHICULE</h1>
<% @vehicule.photos.each do |photo| %>
  <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
<% end %>
<%= @vehicule.brand %>
<%= @vehicule.price %>
<%= link_to "Book car", new_vehicule_booking_path(@vehicule)  %>